### ISSUE TITLE
Fix the Console

### ISSUE THREAD

**Issue by ttanatb** [engine-buddies/light-vox-engine#12] opened 2018-10-07 07:54 UTC
**Describe the bug**
The console doesn't work

**To Reproduce**
try to std::cout or printf

**Expected behavior**
Something should appear

**Comment by RMichelsen** [comment] 2018-10-07 14:22
Hi, I've tried reproducing the issue but I can't. If I call printf from either `Engine::Run()` or `Engine::CreateConsoleWindow()` I do get output as expected.

**Comment by BenjaFriend** [comment] 2018-10-07 20:29
Closing this issue because you can receive output from the console.

**Closed as completed by BenjaFriend** 2018-10-07 20:29 UTC
Labels: bug, P1
